name: Integration Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  integration-testing:
    name: Integration Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - name: Test action
        id: test-action
        # test with the local checkout of the action
        uses: ./
        with:
          template: https://github.com/cjolowicz/cookiecutter-hypermodern-python
          cookiecutterValues: '{
            "project_name": "integration-test",
          }'
      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.addedReleases }}" == ""
